import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import ConvexClientProvider from "@/providers/ConvexClientProvider";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/providers/Themeprovider";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Briefinly",
  description: "Generated by create next app & supabase",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/briefinly-favicon.png" sizes="any" />
      <body className={poppins.className}>
        <ConvexClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system">
            <Header />
            <div className="min-h-screen">
              {children}
            </div>
            <Footer />
            <Toaster richColors position="top-right" />
          </ThemeProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
